default_platform(:ios)

platform :ios do
  desc "Run tests locally"
  lane :test do
    scan(
      project: "NetflixProject.xcodeproj",
      scheme: "NetflixProject",
      device: "iPhone 17 Pro",
      clean: true,
      xcargs: "-skipMacroValidation"
      only_testing: [
	"NetflixProjectTests"
      ]
    )
  end

  desc "Run CI: tests + debug build"
  lane :ci do
    scan(
      project: "NetflixProject.xcodeproj",
      scheme: "NetflixProject",
      device: "iPhone 17 Pro",
      clean: true,
      xcargs: "-skipMacroValidation"
    )

    build_ios_app(
      project: "NetflixProject.xcodeproj",
      scheme: "NetflixProject",
      configuration: "Debug",
      clean: true,
      skip_package_ipa: true,
      skip_codesigning: true,
      xcargs: "-skipMacroValidation",
      destination: "generic/platform=iOS Simulator"
    )
  end
end